[color-theme]
name = "Dark Forest"
color-preference = "dark"

[color-theme.base]
white = "#ABB2BF"
black = "#201B20"
grey = "#513E4B"
blue = "#61AFEF"
red = "#C01C28"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[color-theme.syntax]
attribute = "#5E5C64"
derive = "#77767B"
attributeBracket = "#77767B"
builtinAttribute = "$cyan"
builtinType = "$cyan"
comment = "#5C6370"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "#62A0EA"
enumMember = "#1C71D8"
union = "#62A0EA"
escape = "$cyan"
field = "$blue"
function = "#F6F5F4"
"function.method" = "#F6F5F4"
interface = "#F66151"
# keyword = "$purple"
keyword = "#FFA348"
method = "#F6F5F4"
number = "$yellow"
property = "#BF8500"
selfKeyword = "#8FF0A4"
string = "#B5835A"
struct = "#9141AC"
structure = "$yellow"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
"parameter" = "#2EC27E"
"variable" = "#57E389"
"lifetime" = "#986A44"

[color-theme.ui]
"activity.background" = "$black"
"activity.current" = "$grey"
"completion.background" = "$black"
"completion.current" = "$grey"
"editor.background" = "$black"
"editor.caret" = "$white"
"editor.current_line" = "#303030"
"editor.dim" = "#63452C"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"hover.background" = "$black"
"lapce.active_tab" = "#303030"
"lapce.border" = "#454545"
# "lapce.dropdown_shadow" = "#140F21"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "#303030"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "$black"
"palette.current" = "$grey"
"panel.background" = "#140414"
"panel.current" = "#303030"
"panel.hovered" = "#454545"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#303030"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
drop-shadow-width = 50
